# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ལྕགས་རི་ཤར་ཐུབ་བསྟན་  
tagline:          'Personal website'
description:      '<a href="https://github.com/vajradog" target="_blank">@vajradog</a> is a Tibetan web developer, film editor and a life-long learner based in New York.'
url:              https://vajradog.github.io

author:
  name:           'Thupten Chakrishar'
  url:            https://vajradog.github.io

paginate:         5

# Custom vars
version:          1.0.5

github:
  repo:           https://github.com/vajradog

# Categories
category-list: [Web Development, Video, Graphic]